/*
* Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
* The panic String and panic code declarations	
*
*/


/**
 @file 
*/

#ifndef __PINPANIC_H__
#define __PINPANIC_H__

/** Panic codes generated by the pinplugin */
enum TPinPanics
	{
	/** The Resource file configuration values are not valid */
	EPinPanicInvalidConfigValues=0,
	/** The new Pinlength received from Dialog Interface is incorrect */
	EPinPanicInvalidPinLength=1,
	/** The index of the selected Pin for the Train process otherthan 0 - 3 */
	EPinPanicIncorrectIndex=2
	};

/** The Panic String to Display */
_LIT(KPinPluginPanicString,"PINPLUGIN");

#endif // __PINPANIC_H__

