//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//


PRINT Default Plugin negative test cases (Requires replacement of CenRep initialization files...)

LOAD_SUITE tAuthSvr

//! @SYMTestCaseID SEC-AUT-AUTHSVR-0165
//! @SYMTestCaseDesc Start the Authserver with the Cenrep file containing a blank value for default plugin
//!                  
//! @SYMREQ REQ11230
//! @SYMTestPriority High
//! @SYMTestActions  Remove the Authentication database. Try to start the authserver.
//! @SYMTestExpectedResults Authserver start fails with KErrCorrupt (-20)
//! @SYMDevelopedForRelease Intulo

START_TESTCASE SEC-AUT-AUTHSVR-0165
RUN_TEST_STEP_RESULT 0 100	tAuthSvr 	REMOVE_DBS
RUN_TEST_STEP !RESULT=-20 100	tAuthSvr 	AUTHSVR_CHECK	c:\tauth\tAuthSvr\scripts\tauthsvr2.ini Test0024d
END_TESTCASE SEC-AUT-AUTHSVR-0165

