//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Authentication Server Performance tests...

// Prepare a clone of TAuthSvr to possess authserver's SID.
// This is required for modifying the authserver's central repository file.
// This clone must be deleted at the end of the test.

RUN_PROGRAM 100 SETCAP tAuthSvr.exe 188b0 -SID 102740FC tAuthSvr_new.exe

LOAD_SUITE tAuthSvr
LOAD_SUITE tAuthSvr_new

RUN_UTILS CopyFile C:\tauth\tauthsvr\testdata\pinplugin_inactive.txt C:\pinplugin_inactive.txt
RUN_TEST_STEP_RESULT 0 100	tAuthSvr_new 	INIT_CENREP c:\tauth\tAuthSvr\scripts\tauthsvr2.ini defaultplugin1
RUN_UTILS DeleteFile  C:\t_pinplugindlg_in.dat
RUN_UTILS DeleteFile  C:\t_pinplugindlg_out.dat

START_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0001
RUN_UTILS DELETEDIRECTORY C:\testplugin_active\
RUN_TEST_STEP_RESULT 0 100	tAuthSvr 	REMOVE_DBS
RUN_TEST_STEP_RESULT 0 100	tAuthSvr 	OOM_TEST	c:\tauth\tAuthSvr\scripts\tauthsvr_performance.ini Test0001
END_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0001

START_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0002
RUN_TEST_STEP_RESULT 0 100	tAuthSvr 	OOM_TEST	c:\tauth\tAuthSvr\scripts\tauthsvr_performance.ini Test0002
END_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0002

START_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0003
RUN_TEST_STEP_RESULT 0 100	tAuthSvr 	OOM_TEST	c:\tauth\tAuthSvr\scripts\tauthsvr_performance.ini Test0003
END_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0003

START_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0004
RUN_TEST_STEP !Result=0 100	tAuthSvr 	REMOVE_DBS
RUN_TEST_STEP !Result=0 100	tAuthSvr 	OOM_TEST	c:\tauth\tAuthSvr\scripts\tauthsvr_performance.ini Test0004
END_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0004

// authenticate with 2 plugins.
START_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0005
RUN_TEST_STEP_RESULT 0 100	tAuthSvr 	OOM_TEST	c:\tauth\tAuthSvr\scripts\tauthsvr_performance.ini Test0005
END_TESTCASE SEC-AUT-AUTHSVR-PERFORMANCE-TEST0005

RUN_UTILS DeleteFile  C:\pinplugin_inactive.txt