//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//

PRINT Post Market Plugin tests with KEnablePostMarketAuthenticationPlugins enabled...

// Prepare a clone of TAuthSvr to possess authserver's SID.
// This is required for modifying the authserver's central repository file.
// This clone must be deleted at the end of the test.

RUN_PROGRAM 100 SETCAP tAuthSvr.exe 188b0 -SID 102740FC tAuthSvr_new.exe

LOAD_SUITE tAuthSvr
LOAD_SUITE tAuthSvr_new

// This test must be executed in order to set the default plugin, else authserver will never start.

RUN_UTILS DeleteFile C:\pinplugin_inactive.txt
RUN_TEST_STEP_RESULT 0 100	tAuthSvr_new 	INIT_CENREP c:\tauth\tAuthSvr\scripts\tauthsvr2.ini defaultplugin
RUN_UTILS DeleteFile  C:\t_pinplugindlg_in.dat
RUN_UTILS DeleteFile  C:\t_pinplugindlg_out.dat

// The following test is run for KEnablePostMarketAutheticationPlugins set to a negative value,
// in epoc.ini.This test is executed only in winscw.

LOAD_SUITE tAuthSvr

////
//! @SYMTestCaseID 		SEC-AUT-AUTHPOSTMARKETPLUGINENABLED-0001
//! @SYMTestCaseDesc 		Install and uninstall a non-ROM plugin.Verify that the plugin count increments by one post install operation 
//!				and decrements by one post uninstall operation.
//! @SYMREQ 			REQ 11235
//! @SYMTestPriority 		Medium
//! @SYMTestActions  		1)Retrieve the available plugin list before a non-ROM plugin is installed.
//!		     		2)Install non-ROM plugin specified in the ini file.
//!		     		3)Repeat step 1.Verify that the plugin count increments by one.
//!				4)Retrieve the available plugin list before the non-ROM plugin is uninstalled.
//!				5)Uninstall the non-ROM plugin(installed in step 2).
//!		     		6)Repeat step 1.Verify that the plugin count decrements by one.
//!						
//! @SYMTestExpectedResults	Plugin count increments by one post install and decrements by one post uninstall operation.
//! @SYMDevelopedForRelease 	Diran

START_TESTCASE SEC-AUT-AUTHPOSTMARKETPLUGINENABLED-0001
RUN_TEST_STEP_RESULT 0 100	tAuthSvr	POST_MARKET_PLUGIN	c:\tauth\tAuthSvr\scripts\tpostmarketplugin.ini Test0004
END_TESTCASE SEC-AUT-AUTHPOSTMARKETPLUGINENABLED-0001