//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

//! @file
// authentication client server classes tests

LOAD_SUITE tauthcliserv

////
//! @SYMTestCaseID SEC-AUT-AUTHCLISVR-0008
//! @SYMTestCaseDesc	Authentication client server classes test
START_TESTCASE SEC-AUT-AUTHCLISVR-0008
RUN_TEST_STEP 10 tauthcliserv AuthExprBuild
RUN_PANIC_STEP_RESULT 3 AuthServer 10 tauthcliserv AuthExprBadAuthExt
RUN_TEST_STEP 10 tauthcliserv AuthExprHighVer
RUN_TEST_STEP 300 tauthcliserv AuthExprEval
END_TESTCASE SEC-AUT-AUTHCLISVR-0008
 
