//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//! @file
// Recog unit (integration) tests
PRINT Run Cert Recog test

LOAD_SUITE trecogserver

START_TESTCASE recognizeWTLS

//! @SYMTestCaseID SEC-CERTRECOG-WTLS-DEF068542-0001
//! @SYMTestCaseDesc to recognize a wtls certificate passed by File Name
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a wtls certificate
//! @SYMTestExpectedResults application/vnd.wap.wtls-ca-certificate
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByNameWtls1

//! @SYMTestCaseID SEC-CERTRECOG-WTLS-DEF068542-0002
//! @SYMTestCaseDesc to recognize a wtls certificate passed by Buffer
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a wtls certificate
//! @SYMTestExpectedResults application/vnd.wap.wtls-ca-certificate
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByBufferWtls1

//! @SYMTestCaseID SEC-CERTRECOG-WTLS-DEF068542-0003
//! @SYMTestCaseDesc to recognize a wtls certificate passed by File handle
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a wtls certificate
//! @SYMTestExpectedResults application/vnd.wap.wtls-ca-certificate
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByHandleWtls1

END_TESTCASE recognizeWTLS


START_TESTCASE recognizeX509

//! @SYMTestCaseID SEC-CERTRECOG-X509-DEF068542-0001
//! @SYMTestCaseDesc to recognize a x509 CA certificate passed by File Name
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 CA certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByName1

//! @SYMTestCaseID SEC-CERTRECOG-X509-DEF068542-0002
//! @SYMTestCaseDesc to recognize a x509 user certificate passed by File Name
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 user certificate
//! @SYMTestExpectedResults application/x-x509-user-cert
//! @SYMDevelopedForRelease Mike

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByName2

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC11925
//! @SYMTestCaseDesc to recognize a x509 CA certificate with long serial number, passed by File Name
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 CA certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease 

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByName3

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC073075-0007
//! @SYMTestCaseDesc to recognize a x509 v1 certificate passed by File Name
//! @SYMDEF INC073075
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 v1 certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByNamex509v1

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC076296-0001
//! @SYMTestCaseDesc to recognize a x509 certificate without version passed by File Name
//! @SYMDEF INC076296
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 v1 certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByNamex509NoVersion

//! @SYMTestCaseID SEC-CERTRECOG-X509-DEF068542-0003
//! @SYMTestCaseDesc to recognize a x509 CA certificate passed by File handle
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 CA certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByHandle1

//! @SYMTestCaseID SEC-CERTRECOG-X509-DEF068542-0004
//! @SYMTestCaseDesc to recognize a x509 user certificate passed by File handle
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 user certificate
//! @SYMTestExpectedResults application/x-x509-user-cert
//! @SYMDevelopedForRelease Mike

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByHandle2

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC073075-0008
//! @SYMTestCaseDesc to recognize a x509 v1 certificate passed by File handle
//! @SYMDEF INC073075
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 v1 certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByHandlex509v1

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC076296-0002
//! @SYMTestCaseDesc to recognize a x509 certificate without version passed by File handle
//! @SYMDEF INC076296
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 certificate without version
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByHandlex509NoVersion

//! @SYMTestCaseID SEC-CERTRECOG-X509-DEF068542-0005
//! @SYMTestCaseDesc to recognize a x509 CA certificate passed by Buffer
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 CA certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByBuffer1

//! @SYMTestCaseID SEC-CERTRECOG-X509-DEF068542-0006
//! @SYMTestCaseDesc to recognize a x509 user certificate passed by buffer
//! @SYMREQ REQ0000
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 user certificate
//! @SYMTestExpectedResults application/x-x509-user-cert
//! @SYMDevelopedForRelease Mike

RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByBuffer2

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC073075-0009
//! @SYMTestCaseDesc to recognize a x509 v1 certificate passed by buffer
//! @SYMDEF INC073075
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 v1 certificate
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByBufferx509v1

//! @SYMTestCaseID SEC-CERTRECOG-X509-INC076296-0003
//! @SYMTestCaseDesc to recognize a x509 certificate without Version passed by buffer
//! @SYMDEF INC076296
//! @SYMTestPriority Critical
//! @SYMTestActions to recognize a x509 certificate without version
//! @SYMTestExpectedResults application/x-x509-ca-cert
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByBufferx509NoVersion

END_TESTCASE recognizeX509

START_TESTCASE recognizeSerialNumberLength

//! @SYMTestCaseID SEC-CERTRECOG-X509-PDEF095884-0001
//! @SYMTestCaseDesc To recognize a x509 certificate serial number length set to 0xFF 
//!					 passed by file name.
//! @SYMDEF PDEF095884
//! @SYMTestPriority Critical
//! @SYMTestActions  To recognize a x509 certificate serial number length set to 0xFF.
//! @SYMTestExpectedResults ENotRecognized
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByNameWsnl

//! @SYMTestCaseID SEC-CERTRECOG-X509-PDEF095884-0002
//! @SYMTestCaseDesc To recognize a x509 certificate serial number length set to 0xFF 
//!					 passed by buffer.
//! @SYMDEF PDEF095884
//! @SYMTestPriority Critical
//! @SYMTestActions  To recognize a x509 certificate serial number length set to 0xFF
//! @SYMTestExpectedResults ENotRecognized
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByBufferWsnl

//! @SYMTestCaseID SEC-CERTRECOG-X509-PDEF095884-0003
//! @SYMTestCaseDesc To recognize a x509 certificate serial number length set to 0xFF 
//!					 passed by file handle.
//! @SYMDEF PDEF095884
//! @SYMTestPriority Critical
//! @SYMTestActions To recognize a x509 certificate serial number length set to 0xFF.
//! @SYMTestExpectedResults ENotRecognized
//! @SYMDevelopedForRelease Mike
RUN_TEST_STEP 100 trecogserver RecogStep c:\trecog\trecogcert.ini PassByHandleWsnl

END_TESTCASE recognizeSerialNumberLength
