//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

// Description:
//
//! @file
// authentication key classes tests

LOAD_SUITE tauthkeys

////
//! @SYMTestCaseID SEC-AUT-AUTHKEYS-0001
//! @SYMTestCaseDesc	Authentication key classes test
START_TESTCASE SEC-AUT-AUTHKEYS-0001
RUN_TEST_STEP 100 tauthkeys PERSIST 
RUN_TEST_STEP 100 tauthkeys ENCRYPT_KEY
END_TESTCASE SEC-AUT-AUTHKEYS-0001
 