//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// authentication plugins tests

LOAD_SUITE tauthplugins

////
//! @SYMTestCaseID SEC-AUT-AUTHPLUGINS-0001
//! @SYMTestCaseDesc	Authentication plugins test
START_TESTCASE SEC-AUT-AUTHPLUGINS-0001
RUN_TEST_STEP 100 tauthplugins INTERFACE 
END_TESTCASE SEC-AUT-AUTHPLUGINS-0001
 